[project]
name = "isda-pptgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=2.2.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "python-pptx>=1.0.2",
    "yt-dlp>=2026.3.17",
]

[project.scripts]
isda-pptgen = "isda_pptgen.main:main"

[tool.ruff.lint]
ignore = ["SLF001"]
[tool.ruff.lint.per-file-ignores]
"duplicate.py" = ["E402"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
